name: Merge PR into student branch

on:
  pull_request_target:
    types: [labeled]
    paths:
      - 'src/**'
      - 'test/**'

jobs:
  merge-to-username-branch:
    name: Merge PR into student's branch
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    env:
      SEMESTER_PREFIX: "2025-fall"

    if: github.event.label.name == 'graded' # only runs when labeled manually

    steps:
      - name: Checkout base repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          token: ${{ secrets.REPO_PUSH_TOKEN }}

      - name: Get PR info
        id: prinfo
        run: |
          echo "username=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT
          echo "head_ref=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT

      - name: Create new branch based on PR's branch and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"

          # Create a new branch from the PR's head ref
          BRANCH="${{ env.SEMESTER_PREFIX }}-${{ steps.prinfo.outputs.username }}"
          git fetch origin ${{ steps.prinfo.outputs.head_ref }}
          git checkout -b "$BRANCH" "origin/${{ steps.prinfo.outputs.head_ref }}"
          git push origin "$BRANCH"

      - name: Update PR base branch and close PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ github.event.pull_request.number }};
            const username = "${{ steps.prinfo.outputs.username }}";
            const headRef = "${{ steps.prinfo.outputs.head_ref }}";
            const baseBranch = `${process.env.SEMESTER_PREFIX}-${username}`;

            // Update the base branch of the PR
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              base: baseBranch
            });

            // Perform the merge
            await github.rest.repos.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: baseBranch,
              head: headRef,
              commit_message: `Auto-merged PR #${prNumber} into ${baseBranch}`
            });

            console.log(`Merged PR #${prNumber} into ${baseBranch}`);
